[Service]
Environment=LTO6_SG_DEV=/dev/sg0
Environment=LTO6_ST_DEV=/dev/st0
Environment=LTO6_NST_DEV=/dev/nst0
ExecStart=
ExecStart=/usr/local/sbin/ltfs-fc-stable-start
TimeoutStartSec=3600
Restart=on-failure
RestartSec=30s
