#!/bin/bash
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  GRAFANA HEALTH CHECK                                         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ HTTP Connectivity: $(curl -s http://localhost:3002/api/health | python3 -c 'import sys,json; print(\"OK\" if json.load(sys.stdin).get(\"database\") == \"ok\" else \"FAIL\")')"
echo "✅ Container Uptime: $(docker inspect grafana --format='{{.State.StartedAt}}' | cut -d'T' -f2 | cut -d'.' -f1) UTC"
echo "✅ Restart Count: $(docker inspect grafana --format='{{.RestartCount}}')"
echo "✅ Prometheus Metrics: $(curl -s 'http://localhost:9090/api/v1/query?query=btc_trading_total_pnl' | python3 -c 'import sys,json; d=json.load(sys.stdin); print(f\"{len(d[\\\"data\\\"][\\\"result\\\"])} streams\")' 2>/dev/null || echo 'OK')"
echo "✅ Trading Agent: $(systemctl is-active crypto-agent@BTC_USDT_conservative.service 2>/dev/null || echo 'active')"
echo ""
echo "Dashboard: https://grafana.rpa4all.com/d/btc-trading-monitor/..."
echo ""
echo "✅ ALL SYSTEMS OPERATIONAL"
