[Unit]
Wants=network.target protonvpn-routing-watchdog.service homelab-lan-gateway.service
After=network.target protonvpn-routing-watchdog.service homelab-lan-gateway.service

[Service]
TimeoutStartSec=90s
StartLimitBurst=10
RestartSec=20s
