#!/bin/bash
# fix-wfdealer-route.sh
# Adiciona rota estática no homelab para que tráfego destined a
# 179.190.60.0/24 (wfdealer.andreta.com.br) vá direto ao roteador
# sem passar pelo NordVPN.
#
# Executar no homelab (192.168.15.2) como root:
#   sudo bash fix-wfdealer-route.sh

set -euo pipefail

TARGET_NET="179.190.60.0/24"
GATEWAY="192.168.15.1"
IFACE=$(ip route get 8.8.8.8 2>/dev/null | grep -v nordlynx | grep -v tun | awk '/dev/{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1);exit}}' | head -1)

echo "=== Fix WFDealer Route ==="
echo "Rede destino:  $TARGET_NET"
echo "Gateway:        $GATEWAY"
echo "Interface:      ${IFACE:-auto}"

# Detectar interface se não detectada
if [ -z "$IFACE" ]; then
    IFACE=$(ip route get "$GATEWAY" 2>/dev/null | awk '/dev/{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1);exit}}' | head -1)
    echo "Interface (via gateway): ${IFACE:-eth-onboard}"
fi
IFACE=${IFACE:-eth-onboard}

# Remover rota existente se houver
echo ""
echo "=== Removendo rota existente (se houver) ==="
ip route del "$TARGET_NET" 2>/dev/null && echo "Rota antiga removida" || echo "Nenhuma rota antiga encontrada"

# Adicionar nova rota
echo ""
echo "=== Adicionando rota ==="
ip route add "$TARGET_NET" via "$GATEWAY" dev "$IFACE" && echo "Rota adicionada com sucesso" || {
    echo "ERRO: Falha ao adicionar rota"
    exit 1
}

# Verificar
echo ""
echo "=== Verificando rota ==="
ip route get 179.190.60.1

# Testar conectividade
echo ""
echo "=== Testando conectividade ==="
if ping -c 2 -W 5 179.190.60.196 >/dev/null 2>&1; then
    echo "PING wfdealer: OK"
else
    echo "PING wfdealer: Sem resposta (pode ser firewall no destino - ICMP bloqueado)"
fi

if curl -s --max-time 10 -o /dev/null -w "HTTP %{http_code}" https://wfdealer.andreta.com.br/LoginAux.aspx?Windows 2>/dev/null; then
    echo ""
    echo "HTTPS wfdealer: OK"
else
    echo ""
    echo "HTTPS wfdealer: Timeout (verificar firewall ou regras VPN)"
fi

# Tornar persistente via netplan ou rc.local
echo ""
echo "=== Persistência ==="
NETPLAN_FILE="/etc/netplan/99-wfdealer-route.yaml"
if [ -d /etc/netplan ]; then
    cat > "$NETPLAN_FILE" << EOF
# Auto-generated by fix-wfdealer-route.sh
# Rota para wfdealer.andreta.com.br (179.190.60.0/24)
network:
  version: 2
  renderer: networkd
  routing-policy:
    - from: 179.190.60.0/24
      table: 100
      priority: 100
    - to: 179.190.60.0/24
      table: 100
      priority: 100
EOF
    echo "Rota persistente salva em $NETPLAN_FILE"
    echo "Para aplicar: sudo netplan apply"
else
    # Fallback: systemd-networkd
    NETWORKD_DIR="/etc/systemd/network"
    if [ -d "$NETWORKD_DIR" ]; then
        cat > "$NETWORKD_DIR/20-wfdealer.route" << EOF
[Route]
Destination=179.190.60.0/24
Gateway=$GATEWAY
Metric=100
EOF
        echo "Rota persistente salva em $NETWORKD_DIR/20-wfdealer.route"
        echo "Para aplicar: sudo systemctl restart systemd-networkd"
    else
        echo "AVISO: Não foi possível salvar rota persistente"
        echo "Adicione manualmente ao boot script ou netplan"
    fi
fi

echo ""
echo "=== Concluído ==="
echo "Status: Rota para 179.190.60.0/24 via $GATEWAY configurada"
