apiVersion: 1

datasources:
  - name: Prometheus
    uid: dfc0w4yioe4u8e
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: 15s
    readOnly: false

  - name: Eddie Bus PostgreSQL
    uid: cfbzi6b6m5gcgb
    type: grafana-postgresql-datasource
    access: proxy
    orgId: 1
    url: 172.17.0.1:5433
    user: postgres
    database: shared_bus
    basicAuth: false
    jsonData:
      postgresVersion: 1500
      sslmode: disable
      timescaledb: false
    secureJsonData:
      password: eddie_memory_2026
    readOnly: false

  - name: BTC Trading PostgreSQL
    uid: btc-trading-pg
    type: grafana-postgresql-datasource
    access: proxy
    orgId: 1
    url: 172.17.0.1:5433
    user: postgres
    database: btc_trading
    basicAuth: false
    jsonData:
      postgresVersion: 1500
      sslmode: disable
      timescaledb: false
    secureJsonData:
      password: eddie_memory_2026
    readOnly: true
